// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoolBooks.Models
{
    public partial class Books
    {
        public Books()
        {
            UserInfo = new HashSet<UserInfo>();
        }

        public int BooksID { get; set; }
        public int UserID { get; set; }
        public int AuthorID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ISBN { get; set; }
        public string ImagePath { get; set; }
        public string IsDeleted { get; set; }
        public DateTime? Created { get; set; }
        public int GenerID { get; set; }

        public virtual Authors Author { get; set; }
        public virtual Genres Gener { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}