// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoolBooks.Models
{
    public partial class Books
    {
        public Books()
        {
            UserInfo = new HashSet<UserInfo>();
        }

        [Key]
        public int BooksID { get; set; }
        public int UserID { get; set; }
        public int AuthorID { get; set; }

        [StringLength(50)]
        [Unicode(false)]
        public string Title { get; set; }

        [StringLength(500)]
        [Unicode(false)]
        public string Description { get; set; }

        [StringLength(30)]
        [Unicode(false)]
        public string ISBN { get; set; }

        [StringLength(450)]
        [Unicode(false)]
        public string ImagePath { get; set; }

        [StringLength(20)]
        [Unicode(false)]
        public string IsDeleted { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }

        public int GenerID { get; set; }

        [ForeignKey(nameof(AuthorID))]
        [InverseProperty(nameof(Authors.Books))]
        public virtual Authors Author { get; set; }

        [ForeignKey(nameof(GenerID))]
        [InverseProperty(nameof(Genres.Books))]
        public virtual Genres Gener { get; set; }

        [InverseProperty("Books")]
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}