// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoolBooks.Models
{
    public partial class Reviews
    {
        public Reviews()
        {
            UserInfo = new HashSet<UserInfo>();
        }

        [Key]
        public int ReviewsID { get; set; }
        public int BookID { get; set; }
        public int UserID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Title { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Text { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Rating { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string IdDeleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }

        [InverseProperty("Reviews")]
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}