// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoolBooks.Models
{
    public partial class Reviews
    {
        public Reviews()
        {
            UserInfo = new HashSet<UserInfo>();
        }

        public int ReviewsID { get; set; }
        public int BookID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string Rating { get; set; }
        public string IdDeleted { get; set; }
        public DateTime? Created { get; set; }

        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}