// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoolBooks.Models
{
    public partial class UserInfo
    {
        public int UserInfoID { get; set; }
        public int UserID { get; set; }
        public int ReviewsID { get; set; }
        public int BooksID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public string Created { get; set; }

        public virtual Books Books { get; set; }
        public virtual Reviews Reviews { get; set; }
    }
}